#!/bin/bash

#SBATCH --job-name=bertopic
#SBATCH --error=../logs/bertopic_%A_%a.err
#SBATCH --output=../logs/bertopic_%j.out
#SBATCH --array=1-3
#SBATCH --time=24:00:00
#SBATCH --ntasks=1
#SBATCH --mem=64GB
#SBATCH --partition=gpu
#SBATCH --gres=gpu:v100:1
#SBATCH --cpus-per-task=8
#SBATCH --account=mdehghan_709

module purge
module restore selfharm
source ../../reddit/bin/activate

srun python bert_modelling.py ${SLURM_ARRAY_TASK_ID}
