#!/bin/bash

#SBATCH --job-name=mClassifier
#SBATCH --error=../logs/mClassifier_%A_%a.err
#SBATCH --output=../logs/mClassifier_%job_%j.out
#SBATCH --array=1-3
#SBATCH --time=12:00:00
#SBATCH --ntasks=1
#SBATCH --mem=8GB
#SBATCH --cpus-per-task=4
#SBATCH --partition=gpu
#SBATCH --account=mdehghan_709

module purge
module restore selfharm
source ../../reddit/bin/activate

srun python moral_classifier.py ${SLURM_ARRAY_TASK_ID}

