#!/bin/bash

#SBATCH --job-name=data_annotate
#SBATCH --error=../logs/data_annotate_%A_%a.err
#SBATCH --output=../logs/data_annotate_%j.out
#SBATCH --array=1-2
#SBATCH --time=12:00:00
#SBATCH --ntasks=1
#SBATCH --mem=64GB
#SBATCH --cpus-per-task=8
#SBATCH --account=mdehghan_709

module purge
module restore selfharm
source ../../reddit/bin/activate

srun python get_annotation_data.py ${SLURM_ARRAY_TASK_ID}

