#!/bin/bash

#SBATCH --job-name=annotate_foundations
#SBATCH --error=../logs/annotate_%A_%a.err
#SBATCH --output=../logs/annotate_%j.out
#SBATCH --array=1-3
#SBATCH --time=12:00:00
#SBATCH --ntasks=1
#SBATCH --mem=64GB
#SBATCH --cpus-per-task=8
#SBATCH --partition=gpu
#SBATCH --gres=gpu:2
#SBATCH --account=mdehghan_709

module purge
module restore selfharm
source ../../reddit/bin/activate

srun python predict_foundations.py ${SLURM_ARRAY_TASK_ID}

